[package]
name = "pargen"
version = "0.6.0"
authors = ["Fabian Schuiki <fschuiki@iis.ee.ethz.ch>"]
edition = "2018"

[dependencies]
clap = "2.33"
lalrpop-util = "0.16"
regex = "1.3"
anyhow = "1.0"
log = "0.4"
env_logger = "0.7"
typed-arena = "2"
itertools = "0.9"

[workspace]
